### ISSUE TITLE
Invalid download URL and SHA1 checksum in keepass.portable package

### ISSUE THREAD

**Issue by pyhedgehog** [dtgm/chocolatey-packages#147]
In line
https://github.com/dtgm/chocolatey-packages/blob/master/automatic/_output/keepass.portable/2.32/tools/chocolateyInstall.ps1#L3
url links to another software (so called keepass-classic = keepass 1.x).
in next line checksum is for KeePass-2.31.zip (i.e. for older version).
Please correct url and checksum to KeePass-2.32.zip.

**Comment by dtgm** [comment]
Thanks filing this issue!

Future packages are fixed with https://github.com/dtgm/chocolatey-packages/commit/428515bb24bfcff023df8ad48baf0494e406fcdf

I've unlisted [2.32](https://chocolatey.org/packages/keepass.portable/2.32) and pushed a fix at [2.32.0.20160313](https://chocolatey.org/packages/keepass.portable/2.32.0.20160313)

Source nupkg files for 2.32.0.20160313: https://github.com/dtgm/chocolatey-packages/commit/5cc96570d8e23555987002d2c8d726e9abf1aa43#diff-aebbbd1678b5f0dcf1d0b3fa50202111
