### ISSUE TITLE
sketchup package improvements

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#230]
Per https://chocolatey.org/packages/sketchup#comment-2710921287
- [ ] install/uninstall failing(?)
- [x] clarify Make/Pro naming in "Trial/Freeware (limited functionality)" section (thanks @teknowledgist)
- [ ] Specify full major version installed (2016) with dynamic text (populated via ketarin)
- [ ] ~~Use specific version URL, not latest.~~ [not possible](https://github.com/dtgm/chocolatey-packages/issues/230#issuecomment-228372008)

**Comment by dtgm** [comment]
@teknowledgist have time to help with this?

**Comment by dtgm** [comment]
"install failing" figure out what needs to change would be most helpful. And any suggestions for 2 and 3 would be appreciated.

**Comment by teknowledgist** [comment]
I'll do what I can.

1) I am not getting any errors on install, only uninstall.  I am not PoSh noob, but I like to think I'm OK.  I say that because the failure is happening in the Get-UninstallRegistryKey.ps1 helper function.  I don't think the line:
`      [array]$foundKey = Get-ItemProperty -Path $keys.PsPath `
                                          -ErrorAction SilentlyContinue `
                         | Where-Object { $_.DisplayName -like $softwareName }
`
works.  In PoSh v2, you can't extract the properties of an array like $keys.pspath;  It returns null, and both your ChocolateyUninstall.ps1 and the AutoUninstall fails.

**Comment by teknowledgist** [comment]
2) I submitted a PR with what makes sense to me.
3) I have still not had time to play with Ketarin to figure it out.  I'm going to leave that to you.  

I think the package ID is good, and the title is OK.  Adding 2016 to the title would be nice, but the way Chocolatey plops the version immediately after might make it look confusing ("Sketchup Make/Pro 2016 16.1.1449").  I suppose you could put at the very top of the description  "Sketchup 2016".

**Comment by teknowledgist** [comment]
According to [this](http://help.sketchup.com/en/setting-up#installing-new), there can be multiple version of Sketchup (2015, 2016, etc.) on a computer at a time.  Maybe this package should be ID'd as "sketchup2016".  That would allow someone to have multiple versions installed via Chocolatey as well as take care of the version "confusion".

**Comment by dtgm** [comment]
1. That's important. Thanks for bringing it to my attention. I wrote the extension so that was an oversight on my part about using PsPath. Can I ask why you are still using v2? I'm just wondering if maybe the community feed pkgs should step up to require v3.
2. Merged. Good job.
3. No worries, much easier to do on my end anyway. More interested in your opinion about where. I'm somewhat both for and against putting it in title....you bring up a good point. So beginning of desc, change  
`SketchUp is a...`  
`SketchUp 2016 is a...`
4. I'm against multiple ids with major versions, mostly because it makes everything more complicated. For the user, they can't do `choco upgrade sketchup` and get the new version 2017 next year. They would have to constantly monitor when `sketchup2017` is built. For the maintainer, I don't have any mechanism in place right now to build new pkg ids from scratch. Also, this isn't an issue because you can `choco pin` to a specific version, and install multiple versions with option  `-m, --sxs, --sidebyside, --side-by-side, --allowmultiple, --allow-multiple, --allowmultipleversions, --allow-multiple-versions` ... however, it's good you pointed that out, because the uninstall script should also only point to a specific version. As it is now, uninstalling one package would uninstall every instance of Sketchup and that would likely make someone perturbed.

**Comment by dtgm** [comment]
Added to fix/improvement list to use specific version URLs. You uncover where this is published at all? I know they have them like 
http://dl.trimble.com/sketchup/2013/en/SketchUpPro-2013-0-4124-EN.msi

No luck tho with either:
http://dl.trimble.com/sketchup/2016/en/SketchUpMake-2016-1-1449-EN.msi
http://dl.trimble.com/sketchup/2016/en/SketchUpPro-2016-1-1449-EN.msi

**Comment by teknowledgist** [comment]
1. My test VM is still on PoSh v2 because most of our systems are still v2.  It's the baseline for Win7, so if we are starting with a naked system, we have to start with v2.  I have/use v5 on my production machine, although most of the scripting I do is for other people to use/run (so v2).  My preference would be to stick with v2 for Chocolatey until 2020 when Win7 is EOL.  At that point, I would move to v4 (maybe v5) as a baseline for Win10.  Nobody will be using Win8.1 with v3.

1. Thanks.

1. Works for me.

1. The [release notes with version numbers are here](http://help.sketchup.com/en/article/141303).  I think it is not going to be easy to reliably extract the version number from that.  

Looking at the URLs for downloading previous (major) versions [here](http://www.sketchup.com/download/all), I'm not convinced the numbers in the download match the version number.  Of course, I haven't installed the previous versions, so...  

The apparent "lead guy" of the Sketchup community boards when asked about version numbers says:
> Only major versions are listed. The links always give you the latest MR.

**Comment by dtgm** [comment]
I'm nearly certain that is the plan anyway, and I agree with you.

Re: release notes, article page is what I'm currently using to get the version https://github.com/dtgm/chocolatey-packages/blob/master/ketarin/sketchup.xml#L45 (Doesn't help they have diff ver for 64-bit and 32-bit installers)

Looking at previous versions (2015) I don't even see "70959" noted on the [release notes article](https://help.sketchup.com/en/article/141303) ... so it looks like there isn't a way to automatically build pkgs using a permanent link which means it won't be possible to install previous packages unless someone goes back and manually builds the old package.

Thanks for your help.

**Comment by tunisiano187** [comment]
@gep13  this one Can ne closes as thé développer dont have a installer version, juste web

**Comment by gep13** [comment]
@tunisiano187 sounds like a plan to me.
