### ISSUE TITLE
AdwCleaner runs post install/upgrade

### ISSUE THREAD

**Issue by bcurran3** [dtgm/chocolatey-packages#289]
dtgm - I think I know you're feelings on this, BUT...

The install is technically silent, BUT the program runs post install. It pops up and can be considered an annoyance. I just watched my friend upgrade his programs via Chocolatey and then fire up a fullscreen game to play. Soon as AdwCleaner updated, he got kicked out of his game left wondering "WTF?" He then cntrl-tabbed back to it and all was fine. But could you PLEASE consider stopping the adwcleaner program post install? It won't help with his situation, but users won't be wondering "WTF?" all the time when look at their screen and find AdWCleaner running when they didn't run it.

It's a simple addition to the install script:
if((get-process "adwcleaner" -ea SilentlyContinue) -eq $Null){ 
    Write-Host "adwcleaner currently NOT running." 
  }else{ 
    Write-Host "Stopping adwcleaner process..."
    Stop-Process -processname "adwcleaner"
  }
and the problem would be solved.

p.s. I really think AdwCleaner is a great program, but I don't use Chocolatey to install it because of this problem.

**Comment by bcurran3** [comment]
I know you don't like killing tasks, but since you're already using AHK, how about having it run post install looking for the windows "Malwarebytes AdwCleaner" and send either Alt-F4 or File/Close?

**Comment by dtgm** [comment]
@bcurran3 - Sorry for the delay. I was on holiday without my laptop these last 5 days.

>I think I know you're feelings on this, BUT...

Are those my feelings? Do you remember which discussion we had where I stated that just to help jog my memory?

While I don't remember having that opinion, I can see why I might have said that. I would think it may be unexpected behavior and may interfere with normal operation. For example, say `cup all -y` is automatic and a daily scan is also set in adwcleaner where that scan would daily be interrupted and would be inconvenient and thus I consider poor practice for having unintended effects. For that reason, I usually rather like looking for the Window Title instead of the process name to prevent closing an entire process tree.

But I agree with you it is important to be silent install and am definitely open to adjusting my methods and making exceptions.

>I know you don't like killing tasks, but since you're already using AHK, how about having it run post install looking for the windows "Malwarebytes AdwCleaner" and send either Alt-F4 or File/Close?

It looks like I'm already doing this in the AHK script.  https://chocolatey.org/packages/AdwCleaner#files

`WinClose, AdwCleaner - v, Scan`

I would guess they changed the window title or added another popup. I'll have to take a closer look.  Thanks for reporting and the sample code. 👍

**Comment by bcurran3** [comment]
I think we're seeing eye-to-eye: the goal is to not have the AdwCleaner window left running on the screen after an install or upgrade; it causes failures in background updates.

**Comment by bcurran3** [comment]
Closing as I now maintain this package and the issue has been resolved by me.
