### ISSUE TITLE
Telegram: Please allow system-wide installations

### ISSUE THREAD

**Issue by terrycloth** [dtgm/chocolatey-packages#303]
Installing under the invoking user's `AppData` directory is useful for *unprivileged users* who want to use their favorite software, I guess, but it's a little annoying for *administrators* of multi-user machines, because then each user needs to maintain their own copy of each application. And I think it's largely irrelevant for single-user machines, because the owner and only user of the computer should easily be able to run as admin.

**Comment by ferventcoder** [comment]
The package simply defers to the software default install location - https://github.com/dtgm/chocolatey-packages/blob/306eacbce5639b9b79b923f2244f0a6159807bf4/automatic/telegram.install/tools/chocolateyInstall.ps1

**Comment by dtgm** [comment]
@terrycloth It is still an issue for single-user machines because installs to `ProgramFiles` is also more secure due to UAC. Regardless, like ferventcoder said, install location preference needs to be added to the installer by telegram. You will probably want to add to this discussion https://github.com/telegramdesktop/tdesktop/issues/2355
