### ISSUE TITLE
WakeMeOnLan version 1.83 available

### ISSUE THREAD

**Issue by jedfrechette** [dtgm/chocolatey-packages#372]
WakeMeOnLan version 1.83 is available at:

http://www.nirsoft.net/utils/wake_on_lan.html

The current 1.82 package on ChocolateyPackages doesn't install because the checksum no longer matches the downloaded file.

**Comment by gep13** [comment]
@jedfrechette are you in a position to provide a PR to update this package?  Thanks!

**Comment by jedfrechette** [comment]
@gep13 I'm afraid I don't have the bandwidth to put together a pull request at the moment.

I took a brief look at the automatic packaging as I've only built manual packages to date, but it wasn't entirely obvious to me what the intended setup was. The README in this repo points to ChocolateyPackageUpdater, but the Chocolatey.org docs indicate that it is depreciated. Is the Updater still what needs to be setup for testing automatic packages?

**Comment by gep13** [comment]
> @jedfrechette said...
Is the Updater still what needs to be setup for testing automatic packages?

When this repository, with it's almost 900 packages was set up, ChocolateyPackageUpdater and Ketarin was the best solution available.  Since then, AU has come along which is a lot more approachable for most people.  However, given the sheer number of packages that are in this repo, there hasn't been a conversion to AU as of yet, so we are still using ChocolateyPackageUpdater.

**Comment by CWempe** [comment]
Any news about this?

**Comment by tunisiano187** [comment]
The latest version as been pushed,  i'm the new maintainer.
This issue can be closed.

Thank you

**Comment by gep13** [comment]
@tunisiano187 have the files been removed from the repo?
