### ISSUE TITLE
[LinkShellExtension] Hash for installer changed

### ISSUE THREAD

**Issue by coldacid** [dtgm/chocolatey-packages#383]
Per http://disq.us/p/1qv984d the installer hash changed at least 16 days ago and the package will no longer install without needing to ignore the hash. Seems there's also been a change in supported VC redist as well per same comment.

**Comment by dtgm** [comment]
Which version are you trying to install? The checksum appears to be correct in the package in the latest version [3.8.6.90](https://chocolatey.org/packages/LinkShellExtension/3.8.6.90). Previous versions will fail because the installer URL only points to the latest version and gets overwritten by the developer on each new release.

**Comment by coldacid** [comment]
It appears to be 3.8.6.501 again. 😕

**Comment by dtgm** [comment]
[3.8.6.501](https://chocolatey.org/packages/LinkShellExtension/3.8.6.501) is unlisted. The only way that package should be installed is if you specify with option `-version 3.8.6.501` ... you could also have that version pinned with chocolatey so it is not upgrading.

I'm closing as the hash hasn't changed from latest version.
