### ISSUE TITLE
kvrt not installing: checksum mismatch

### ISSUE THREAD

**Issue by wjk** [dtgm/chocolatey-packages#65]
Several times now, when I have tried to install the `kvrt` package, it refuses to run the installer because the SHA-1 checksum is invalid (expected `e197b0453dd1ba51b635e1c7ff2e8e67da1dddb6`, got `A5660C286D3D31554DAD2DDD36F7587E6F292D5F`). This has been occuring for a few months now. Do you have any idea why this might occur? Thanks!

**Comment by dtgm** [comment]
Your frustration is primarily because this program gets updated almost daily and unfortunately the URL is self-deprecating; `http://devbuilds.kaspersky-labs.com/devbuilds/KVRT/latest/full/KVRT.exe` So regardless of the package version, chocolatey always downloads from the same URL. This means if you try to install the program after they publish an updated bin and before I detect it, the checksum will fail.

However, that wasn't the issue this time. Since you wrote this 21 Nov I'm guessing you received this error on that day or the day before. Looking at the gallery there is a gap.

```
Kaspersky Virus Removal Tool 2015.11.24 	10 	Tue, November 24, 2015 	approved
Kaspersky Virus Removal Tool 2015.11.23 	4 	Mon, November 23, 2015 	approved
                missing  --> 2015.11.20 <--
Kaspersky Virus Removal Tool 2015.11.19 	17 	Thu, November 19, 2015 	approved
Kaspersky Virus Removal Tool 2015.11.18 	4 	Wed, November 18, 2015 	approved
```

Looking at my build log, version `2015.11.20` should have been uploaded but it failed to calculate the checksum and build the nupkg. You can see this here https://github.com/dtgm/chocolatey-packages/blob/master/automatic/_output/kvrt/2015.11.20/tools/chocolateyInstall.ps1#L3

You could disable the option to verify the checksum before installing, but I don't recommend that.

**Comment by dtgm** [comment]
I just tried installing kvrt and the checksum has already expired so I did some more digging...

It looks like they published the version I'm checksumming in the latest package, [2015.12.06](https://chocolatey.org/packages/kvrt/2015.12.06), at 00:40. And then they published a new binary 46 minutes later at 01:26.

I'm going to revise the version to include hour and min. Hopefully this helps keep it up to date.
