### ISSUE TITLE
FolderTimeUpdate out of date

### ISSUE THREAD

**Issue by benjaminmesser** [dtgm/chocolatey-packages#650]
I know this package is meant to auto-update, but something is obviously broken in that pipeline. The newest version is 1.72 and the choco page is still showing 1.55. Newest checksum is B49E8BC044893F978E9A8E60714E29F32FA6BA3F929C4AAA58B74B536E160E3E. Would appreciate an update when possible.

**Comment by gep13** [comment]
@benjaminmesser thank you for reaching out about this package.

@dtgm is no longer an active maintainer of Chocolatey packages, and as a result, there is no guarantee that his packages will continue to be updated.

It may be the case that other maintainers may be able to help with packaging of this application, and you can raise an issue [here](https://github.com/chocolatey-community/chocolatey-package-requests), or if you are able to help, you could become a maintainer yourself.

For now, I am going to close off this issue here, as it is unlikely that it will be worked on in this repository.
