### ISSUE TITLE
General question: Automatic push?

### ISSUE THREAD

**Issue by ComFreek** [dtgm/chocolatey-packages#7]
Hi dtgm,

may I ask you whether you automatically push packages (i.e. not using /disablepush)?
If not, how do you know when a new version has been downloaded?

**Comment by dtgm** [comment]
@ComFreek, 

Yup, I automatically push packages.  I only use `--nopush` or `--disablepush` during testing a package.

I have one master command for all packages and then set a per-app variable as needed for testing/fixing an app.  So I have 

`File > Settings > Commands > Before updating an application` 

set to 

`chocopkgup {nopush} --packagename={appname} --version={version} --pg="{packageGuid}" --url="{preupdate-url}" --urlx64="{url64}" --packagepath="{file}" --checksum="{checksum}" --c64="{checksumx64}" --debug`

Then each package in ketarin has its own variable `nopush` which contains the text `--nopush`

To push the package, you can either set the variable `nopush` to null, rename `nopush` to anything else, or just delete `nopush` var from that app.  Personally, I rename nopush to yopush so I just have to edit one letter to toggle between the desired states; HighlightVar>F2>Home>Delete>y|n>Enter

**Comment by dtgm** [comment]
The downside to adding `chocopkgup ...` to `File > Settings > Commands` is __all__ packages added to Ketarin initialize `chocopkgup ...` for the state it is set to, one of:

* Before updating an application
* After updating an application
* After updating all applications

Meaning hopefully you are only using Ketarin for creating Chocolatey nupkg files, as all apps get pushed (or at least attempted to be packaged) when an update is detected.  However, if a directory is not matching **exactly** the application name in your PackagesFolder (set in `$Env:ChocolateyInstall\lib\ChocolateyPackageUpdater.x.x.x.x\tools\chocopkgup\chocopkgup.exe.config`) chocopkgup fails silently and Ketarin continues just fine.  So while you could use this method without harm, if you want to use different commands for different Ketarin applications.  You will want to move the `chocopkgup ...` command directly to each package. `App>Edit>Commands>Execute ... before downloading`

**Comment by dtgm** [comment]
@ComFreek 
>how do you know when a new version has been downloaded?

You could add something after the `chocopkgup...` command so it would look something like

`chocopkgup...
echo {appname} updated to {version} on {dddd} at {HH}:{mm} >> %UserProfile%\Dropbox\chocolatey-updates\{appname}.txt`

You could then sort that directory by date modified to see a list of when packages were updated.  

Changes would show up on https://www.dropbox.com/events so you could review them online with your account there.

Otherwise you could use a command-line app to publish to a twitter feed or something.

`cmd /c pushtotwitterprogram --options --text="{{appname} updated to {version} on {dddd} at {HH}:{mm}"

But this doesn't necessarily mean the package was pushed, for that you might want to look at the exit code of chocopkgup, but even then you cannot be certain.  So you may want to use the chocolatey odata feed https://chocolatey.org/api/v2/

Personally, I don't have time to monitor another "feed" so I don't care to be alerted about this information.  I just have taskschd.msc to do a routine `choco upgrade all` and get it from chocolatey.org like everyone else.

**Comment by ComFreek** [comment]
@dtgm Thank you very much for the detailed information!

I have built a PowerShell script which uses [mailsend](https://github.com/muquit/mailsend) to send me a mail in case of updates. It is called after an update (`File > Settings > Commands > After updating an application`):

```
powershell P:\Chocolatey\chocolatey-mailsend.ps1 -appName "{appname} {nopush}" -version "{version}"
```

The script:
```
param(
  [string] $appName,
  [string] $version
)

$mailSendPath = Join-Path $PSScriptRoot "my-packages/mailsend.exe"

$from = "CENSORED"
$user = $from
$pass = "CENSORED"

$subject = "[CHOCO UPDATE] $appName --> $version"
$message = "This is an automatically sent mail from chocolatey-mailsend.ps1 in response to Ketarin's update process"

$to = "[CENSORED]"
$argumentList = @(
  "-f", ("`"" + $from + "`""),
  "-user", ("`"" + $user + "`""),
  "-pass", ("`"" + $pass + "`"")
  "-smtp", "smtp-mail.outlook.com",
  "-t", ("`"" + $to + "`""),
  "-starttls",
  "-port", "587",
  "-auth",
  "+cc", "+bc",
  "-sub", ("`"" + $subject + "`""),
  "-M", ("`"" + $message + "`"")
);

Start-Process $mailSendPath -ArgumentList $argumentList
```

PS: You mentioned `$Env:ChocolateyInstall\lib\ChocolateyPackageUpdater.x.x.x.x\tools\chocopkgup\chocopkgup.exe.config` as the path to chocopkgup. On my system it is `C:\tools\ChocolateyPackageUpdater`, however, yours exists as well, but only the first one is within my PATH.

**Comment by dtgm** [comment]
@ComFreek Thanks for sharing back!

Also, you are correct, it gets installed to both locations.  But doesn't run from the path `$Env:ChocolateyInstall\lib\...` I always forget this. :(

<pre>
PS C:\>  get-command -syntax chocopkgup`
C:\bin\ChocolateyPackageUpdater\chocopkgup.exe
</pre>

C:\tools (for you) == C:\bin (for me) == which since version 0.6.4, are set by internal choco Get-BinRoot helper function which reads the value you set at `[System.Environment]::GetEnvironmentVariables([System.EnvironmentVariableTarget]::User).ChocolateyBinRoot`

If you do not set the `ChocolateyBinRoot` user variable, it may default to C:\tools (?)

Keep in mind if you `cinst ChocolateyPackageUpdater -force` the files in $Env:ChocolateyBinRoot\ChocolateyPackageUpdater\` are overwritten with the files at `$Env:ChocolateyInstall\lib\ChocolateyPackageUpdater.x.x.x.x\tools\chocopkgup\`

So for every upgrade, your config files will become obsolete, which for a package that upgrades all other packages doesn't seem like a very solid plan or is very intuitive :/
(this is https://github.com/chocolatey/chocolatey/issues/650)

For now, you probably will want to edit the files at `$Env:ChocolateyInstall\lib\ChocolateyPackageUpdater.x.x.x.x\tools\chocopkgup\` and then do a `cinst ChocolateyPackageUpdater -force` or manually copy them over so you retain a backup.  You will then have to manually copy the files over when a new package is issued.

**Comment by ComFreek** [comment]
> If you do not set the  ChocolateyBinRoot  user variable, it may default to C:\tools (?)

You're right! I've just found [chocolatey/src/helpers/functions/Get-BindRoot.ps1#L10](https://github.com/chocolatey/chocolatey/blob/db4bc6a83a0c329b6a9b54691d30650a8d4a57d7/src/helpers/functions/Get-BinRoot.ps1#L10). Also, I don't have such an environment variable.

Thanks for the notes on the config file. I copied it to a save location.

**Comment by dtgm** [comment]
Definitely welcome!  My packages didn't update for over at least a month the first time this happened. Then not realising there was another config file.  Much pain.

For that reason, your email script will most likely be put to good use.  :) You might also want to look at an open-source package I maintain `cinst blat` for a light command-line MTA.  Also, there is `Send-MailMessage`.

Do you happen to know the difference between posh built-in `Send-MailMessage` and `mailsend`?

**Comment by ComFreek** [comment]
`mailsend` is a generic executable which can be used by any Windows program. I didn't know of `Send-MailMessage`, but I have now rewritten my script to use that function: https://gist.github.com/ComFreek/5b054ae1701cc46042df

**Comment by dtgm** [comment]
Very nice!  Thank you for sharing!
