### ISSUE TITLE
eventghost: please update to r1722 (important keyboard fix)

### ISSUE THREAD

**Issue by dreamcat4** [dtgm/chocolatey-packages#99]
Hi there,
The eventghost has been updated recently. Now it might seem like another small, incremental update however in there they have fixed an important and longstanding issue with the Keyboard Plugin (which used to break whenever Win+G was pressed).

http://www.eventghost.net/forum/viewtopic.php?f=4&t=7752&sid=a559fc69554a70562dd4b10a82df81bf&p=38808#p38696

The new binary has already been released so lets also please update the choco pkg

http://www.eventghost.org/downloads/EventGhost_0.4.1.r1722_Setup.exe

Many thanks

**Comment by dreamcat4** [comment]
I see from your repo here that it is an automatic pkg:

https://github.com/dtgm/chocolatey-packages/tree/master/automatic/eventghost

Not sure what that means exactly. Maybe its `$version` found / derived elsewhere.

**Comment by dreamcat4** [comment]
Hi again. 24 hrs has passed and no updated pkg on chocolatey. Can you confirm that it will rebuild/t soon?

**Comment by dtgm** [comment]
@dreamcat4 Thanks for opening this issue! Somehow I overlooked it though...

eventghost didn't get updated right away because I had an issue with the build machine almost exactly when this program was updated. See https://github.com/dtgm/chocolatey-packages/issues/103

eventghost was finally updated automatically about 40 hours after you opened this issue: 2016-02-05 02:41 UTC. Packages should be updated within 24 hours of program releases.

https://github.com/dtgm/chocolatey-packages/commit/2bd8ae9d1eed050f011189a2e978060ca7514b41#diff-d20db285437a9277249d8ea787bd4d4e
https://chocolatey.org/packages/eventghost/0.4.1.1722

**Comment by dtgm** [comment]
timeline

**2016-02-05 02:41 UTC** -- pushed to chocolatey.org (latest recognized = 0.4.1.1710, installing requires manually specifying `-version 0.4.1.1722`)
**2016-02-05 03:17 UTC** -- passed automated testing
**2016-02-05 19:37 UTC** -- manually approved (latest recognized = 0.4.1.1722)

eventghost was also marked `trusted` at last review meaning future versions will automatically be approved after passing automated testing (~30 minutes after a package is uploaded to chocolatey.org)

**Comment by dreamcat4** [comment]
Thanks @dtgm. Appreciate it.
